import type { FieldDef } from './types'

export const genericNodeFields: Record<string, FieldDef[]> = {
  spreadsheetNode: [
    { key: 'format', label: 'Format', type: 'select', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel (XLSX)' }, { value: 'google_sheets', label: 'Google Sheets' }] },
    { key: 'operation', label: 'Operation', type: 'select', options: [{ value: 'import', label: 'Import' }, { value: 'export', label: 'Export' }, { value: 'transform', label: 'Transform' }] },
    { key: 'filePath', label: 'File Path', type: 'text', placeholder: '/path/to/file.csv' },
    { key: 'sheetName', label: 'Sheet Name', type: 'text', placeholder: 'Sheet1' },
  ],
  emailInboxNode: [
    { key: 'protocol', label: 'Protocol', type: 'select', options: [{ value: 'imap', label: 'IMAP' }, { value: 'pop3', label: 'POP3' }] },
    { key: 'host', label: 'Host', type: 'text', placeholder: 'imap.gmail.com' },
    { key: 'port', label: 'Port', type: 'number', placeholder: '993' },
    { key: 'email', label: 'Email', type: 'text', placeholder: 'user@example.com' },
    { key: 'password', label: 'Password', type: 'password', placeholder: 'App password' },
    { key: 'filterUnread', label: 'Unread Only', type: 'checkbox' },
  ],
  webSearchNode: [
    { key: 'engine', label: 'Engine', type: 'select', options: [{ value: 'searxng', label: 'SearXNG' }, { value: 'duckduckgo', label: 'DuckDuckGo' }] },
    { key: 'engineUrl', label: 'Engine URL', type: 'text', placeholder: 'http://localhost:8888' },
    { key: 'maxResults', label: 'Max Results', type: 'number', placeholder: '10' },
  ],
  personalityNode: [
    { key: 'persona', label: 'Persona', type: 'select', options: [{ value: 'professional', label: 'Professional' }, { value: 'technical', label: 'Technical' }, { value: 'friendly', label: 'Friendly' }, { value: 'legal', label: 'Legal Expert' }] },
    { key: 'tone', label: 'Tone', type: 'select', options: [{ value: 'formal', label: 'Formal' }, { value: 'casual', label: 'Casual' }, { value: 'concise', label: 'Concise' }, { value: 'detailed', label: 'Detailed' }] },
    { key: 'language', label: 'Language', type: 'select', options: [{ value: 'en', label: 'English' }, { value: 'es', label: 'Spanish' }, { value: 'fr', label: 'French' }, { value: 'de', label: 'German' }, { value: 'it', label: 'Italian' }, { value: 'nl', label: 'Dutch' }] },
    { key: 'customPrompt', label: 'Custom Instructions', type: 'textarea', placeholder: 'Additional instructions for the AI personality...' },
  ],
  auditNode: [
    { key: 'auditLevel', label: 'Audit Level', type: 'select', options: [{ value: 'full', label: 'Full' }, { value: 'summary', label: 'Summary' }, { value: 'errors', label: 'Errors Only' }] },
    { key: 'retentionDays', label: 'Retention (days)', type: 'number', placeholder: '90' },
    { key: 'logFormat', label: 'Log Format', type: 'select', options: [{ value: 'json', label: 'JSON' }, { value: 'csv', label: 'CSV' }, { value: 'syslog', label: 'Syslog' }] },
    { key: 'enabled', label: 'Enabled', type: 'checkbox' },
  ],
  codeReviewNode: [
    { key: 'reviewType', label: 'Review Type', type: 'select', options: [{ value: 'security', label: 'Security' }, { value: 'style', label: 'Style' }, { value: 'bugs', label: 'Bug Detection' }, { value: 'performance', label: 'Performance' }, { value: 'all', label: 'Full Review' }] },
    { key: 'language', label: 'Language', type: 'select', options: [{ value: 'auto', label: 'Auto-detect' }, { value: 'python', label: 'Python' }, { value: 'javascript', label: 'JavaScript' }, { value: 'typescript', label: 'TypeScript' }, { value: 'go', label: 'Go' }, { value: 'rust', label: 'Rust' }] },
    { key: 'minSeverity', label: 'Min Severity', type: 'select', options: [{ value: 'low', label: 'Low' }, { value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }, { value: 'critical', label: 'Critical' }] },
    { key: 'sourceUrl', label: 'Source URL', type: 'text', placeholder: 'https://github.com/repo/...' },
  ],
  mcpContextNode: [
    { key: 'protocol', label: 'Protocol', type: 'select', options: [{ value: 'stdio', label: 'STDIO' }, { value: 'sse', label: 'SSE' }, { value: 'streamable-http', label: 'Streamable HTTP' }] },
    { key: 'serverUrl', label: 'Server URL', type: 'text', placeholder: 'http://localhost:3000/mcp' },
    { key: 'serverCommand', label: 'Server Command', type: 'text', placeholder: 'npx -y @modelcontextprotocol/server-...' },
    { key: 'toolCount', label: 'Available Tools', type: 'number', placeholder: '0' },
  ],
  conditionalNode: [
    { key: 'field', label: 'Field / Key', type: 'text', placeholder: 'e.g. status, score, result' },
    { key: 'operator', label: 'Operator', type: 'select', options: [{ value: 'equals', label: 'Equals' }, { value: 'not_equals', label: 'Not Equals' }, { value: 'contains', label: 'Contains' }, { value: 'greater_than', label: 'Greater Than' }, { value: 'less_than', label: 'Less Than' }, { value: 'is_empty', label: 'Is Empty' }, { value: 'is_not_empty', label: 'Is Not Empty' }, { value: 'regex', label: 'Regex Match' }] },
    { key: 'value', label: 'Value', type: 'text', placeholder: 'Comparison value' },
  ],
  approvalGateNode: [
    { key: 'approvalType', label: 'Approval Type', type: 'select', options: [{ value: 'single', label: 'Single Approver' }, { value: 'multi', label: 'Multi-Level Chain' }, { value: 'quorum', label: 'Quorum (Majority)' }] },
    { key: 'requireAll', label: 'Require All Approvers', type: 'checkbox' },
    { key: 'timeoutHours', label: 'Timeout (hours)', type: 'number', placeholder: '24' },
    { key: 'escalationEmail', label: 'Escalation Email', type: 'text', placeholder: 'manager@company.com' },
  ],
  complianceDashboardNode: [
    { key: 'reportFormat', label: 'Report Format', type: 'select', options: [{ value: 'pdf', label: 'PDF' }, { value: 'docx', label: 'DOCX' }, { value: 'html', label: 'HTML' }, { value: 'json', label: 'JSON' }] },
    { key: 'autoGenerate', label: 'Auto-Generate Reports', type: 'checkbox' },
    { key: 'includeEvidence', label: 'Include Evidence', type: 'checkbox' },
    { key: 'reportTitle', label: 'Report Title', type: 'text', placeholder: 'Compliance Assessment Report' },
  ],
  modelRegistryNode: [
    { key: 'modelName', label: 'Model Name', type: 'text', placeholder: 'e.g. llama3.2, mistral' },
    { key: 'riskLevel', label: 'EU AI Act Risk Level', type: 'select', options: [{ value: 'unclassified', label: 'Unclassified' }, { value: 'minimal', label: 'Minimal Risk' }, { value: 'limited', label: 'Limited Risk' }, { value: 'high', label: 'High Risk' }, { value: 'unacceptable', label: 'Unacceptable Risk' }] },
    { key: 'modelVersion', label: 'Model Version', type: 'text', placeholder: '1.0' },
    { key: 'purpose', label: 'Purpose / Use Case', type: 'textarea', placeholder: 'Describe the model purpose...' },
  ],
  evidenceCollectionNode: [
    { key: 'targetFramework', label: 'Target Framework', type: 'select', options: [{ value: 'soc2', label: 'SOC 2' }, { value: 'iso27001', label: 'ISO 27001' }, { value: 'hipaa', label: 'HIPAA' }, { value: 'gdpr', label: 'GDPR' }, { value: 'eu_ai_act', label: 'EU AI Act' }] },
    { key: 'autoPackage', label: 'Auto-Package Evidence', type: 'checkbox' },
    { key: 'retentionDays', label: 'Retention (days)', type: 'number', placeholder: '365' },
    { key: 'outputPath', label: 'Output Path', type: 'text', placeholder: '/evidence/output/' },
  ],
  biasTestingNode: [
    { key: 'testType', label: 'Test Type', type: 'select', options: [{ value: 'disparate_impact', label: 'Disparate Impact' }, { value: 'demographic_parity', label: 'Demographic Parity' }, { value: 'equalized_odds', label: 'Equalized Odds' }, { value: 'calibration', label: 'Calibration' }] },
    { key: 'threshold', label: 'Pass Threshold', type: 'number', placeholder: '0.8' },
    { key: 'protectedField', label: 'Protected Attribute Field', type: 'text', placeholder: 'e.g. gender, race, age' },
    { key: 'outcomeField', label: 'Outcome Field', type: 'text', placeholder: 'e.g. approved, score' },
  ],
  explainabilityNode: [
    { key: 'method', label: 'Method', type: 'select', options: [{ value: 'feature_importance', label: 'Feature Importance' }, { value: 'counterfactual', label: 'Counterfactual' }, { value: 'decision_trail', label: 'Decision Trail' }, { value: 'shap_proxy', label: 'SHAP Proxy (LLM)' }] },
    { key: 'model', label: 'Explanation Model', type: 'select', options: [{ value: 'llama3.2', label: 'Llama 3.2' }, { value: 'mistral', label: 'Mistral' }, { value: 'codellama', label: 'CodeLlama' }] },
    { key: 'detailLevel', label: 'Detail Level', type: 'select', options: [{ value: 'summary', label: 'Summary' }, { value: 'detailed', label: 'Detailed' }, { value: 'technical', label: 'Technical' }] },
  ],
  redTeamingNode: [
    { key: 'minSeverity', label: 'Min Severity', type: 'select', options: [{ value: 'low', label: 'Low' }, { value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }, { value: 'critical', label: 'Critical' }] },
    { key: 'iterations', label: 'Iterations', type: 'number', placeholder: '10' },
    { key: 'targetModel', label: 'Target Model', type: 'text', placeholder: 'llama3.2' },
    { key: 'customPrompts', label: 'Custom Attack Prompts', type: 'textarea', placeholder: 'One prompt per line...' },
  ],
  driftDetectionNode: [
    { key: 'metric', label: 'Drift Metric', type: 'select', options: [{ value: 'output_similarity', label: 'Output Similarity' }, { value: 'statistical', label: 'Statistical (KS Test)' }, { value: 'embedding_distance', label: 'Embedding Distance' }] },
    { key: 'driftThreshold', label: 'Drift Threshold', type: 'number', placeholder: '0.15' },
    { key: 'schedule', label: 'Schedule', type: 'select', options: [{ value: 'hourly', label: 'Hourly' }, { value: 'daily', label: 'Daily' }, { value: 'weekly', label: 'Weekly' }] },
    { key: 'alertEmail', label: 'Alert Email', type: 'text', placeholder: 'alerts@company.com' },
  ],
  notificationNode: [
    { key: 'channel', label: 'Channel', type: 'select', options: [{ value: 'slack', label: 'Slack' }, { value: 'teams', label: 'MS Teams' }, { value: 'sms', label: 'SMS (Twilio)' }, { value: 'webhook', label: 'Webhook' }, { value: 'email', label: 'Email' }] },
    { key: 'webhookUrl', label: 'Webhook / API URL', type: 'text', placeholder: 'https://hooks.slack.com/...' },
    { key: 'messageTemplate', label: 'Message Template', type: 'textarea', placeholder: 'Workflow {workflowName} completed: {result}' },
    { key: 'onFailureOnly', label: 'Only On Failure', type: 'checkbox' },
  ],
  encryptionNode: [
    { key: 'algorithm', label: 'Algorithm', type: 'select', options: [{ value: 'aes-256-gcm', label: 'AES-256-GCM' }, { value: 'aes-256-cbc', label: 'AES-256-CBC' }, { value: 'rsa-oaep', label: 'RSA-OAEP' }, { value: 'chacha20', label: 'ChaCha20-Poly1305' }] },
    { key: 'operation', label: 'Operation', type: 'select', options: [{ value: 'encrypt', label: 'Encrypt' }, { value: 'decrypt', label: 'Decrypt' }, { value: 'sign', label: 'Digital Sign' }, { value: 'verify', label: 'Verify Signature' }] },
    { key: 'keyId', label: 'Key ID / Reference', type: 'text', placeholder: 'key-001 or path to key file' },
  ],
  webhookGatewayNode: [
    { key: 'method', label: 'HTTP Method', type: 'select', options: [{ value: 'GET', label: 'GET' }, { value: 'POST', label: 'POST' }, { value: 'PUT', label: 'PUT' }, { value: 'DELETE', label: 'DELETE' }] },
    { key: 'authType', label: 'Auth Type', type: 'select', options: [{ value: 'none', label: 'None' }, { value: 'api_key', label: 'API Key' }, { value: 'bearer', label: 'Bearer Token' }, { value: 'basic', label: 'Basic Auth' }] },
    { key: 'endpointPath', label: 'Endpoint Path', type: 'text', placeholder: '/api/workflow/execute' },
    { key: 'rateLimit', label: 'Rate Limit (req/min)', type: 'number', placeholder: '60' },
  ],
  subWorkflowNode: [
    { key: 'targetWorkflowId', label: 'Target Workflow ID', type: 'text', placeholder: 'Workflow ID to invoke' },
    { key: 'targetWorkflowName', label: 'Workflow Name', type: 'text', placeholder: 'Sub-workflow name' },
    { key: 'passData', label: 'Pass Data to Sub-Workflow', type: 'checkbox' },
    { key: 'waitForCompletion', label: 'Wait for Completion', type: 'checkbox' },
  ],
  phiClassificationNode: [
    { key: 'deidentMethod', label: 'De-identification Method', type: 'select', options: [{ value: 'safe_harbor', label: 'Safe Harbor (18 IDs)' }, { value: 'expert_determination', label: 'Expert Determination' }, { value: 'limited_dataset', label: 'Limited Dataset' }] },
    { key: 'replacementStrategy', label: 'Replacement', type: 'select', options: [{ value: 'redact', label: 'Redact [PHI]' }, { value: 'pseudonymize', label: 'Pseudonymize' }, { value: 'generalize', label: 'Generalize' }] },
    { key: 'customPatterns', label: 'Custom PHI Patterns', type: 'textarea', placeholder: 'Additional regex patterns, one per line' },
  ],
  fairLendingNode: [
    { key: 'regulation', label: 'Regulation', type: 'select', options: [{ value: 'ecoa', label: 'ECOA' }, { value: 'reg_b', label: 'Regulation B' }, { value: 'hmda', label: 'HMDA' }, { value: 'cra', label: 'CRA' }] },
    { key: 'analysisType', label: 'Analysis Type', type: 'select', options: [{ value: 'disparate_impact', label: 'Disparate Impact' }, { value: 'disparate_treatment', label: 'Disparate Treatment' }, { value: 'regression', label: 'Regression Analysis' }] },
    { key: 'decisionField', label: 'Decision Field', type: 'text', placeholder: 'e.g. approved, denied' },
    { key: 'threshold', label: 'Impact Threshold', type: 'number', placeholder: '0.8' },
  ],
  claimsAuditNode: [
    { key: 'auditType', label: 'Audit Type', type: 'select', options: [{ value: 'full', label: 'Full Audit' }, { value: 'denial_review', label: 'Denial Review' }, { value: 'sample', label: 'Random Sample' }] },
    { key: 'flagAutoDenials', label: 'Flag Auto-Denials', type: 'checkbox' },
    { key: 'generateExplanation', label: 'Generate Policyholder Explanation', type: 'checkbox' },
    { key: 'model', label: 'Explanation Model', type: 'select', options: [{ value: 'llama3.2', label: 'Llama 3.2' }, { value: 'mistral', label: 'Mistral' }] },
  ],
  consentManagementNode: [
    { key: 'regulation', label: 'Regulation', type: 'select', options: [{ value: 'gdpr', label: 'GDPR Article 7' }, { value: 'hipaa', label: 'HIPAA Authorization' }, { value: 'ccpa', label: 'CCPA' }, { value: 'lgpd', label: 'LGPD' }] },
    { key: 'consentType', label: 'Consent Type', type: 'select', options: [{ value: 'explicit', label: 'Explicit Opt-in' }, { value: 'implied', label: 'Implied' }, { value: 'opt_out', label: 'Opt-out' }] },
    { key: 'blockOnMissing', label: 'Block Processing if No Consent', type: 'checkbox' },
    { key: 'consentField', label: 'Consent Record Field', type: 'text', placeholder: 'e.g. consent_given, authorized' },
  ],
  slackComplianceNode: [
    { key: 'authType', label: 'Authentication', type: 'select', options: [{ value: 'oauth', label: 'OAuth 2.0' }, { value: 'token', label: 'API Token' }] },
    { key: 'workspaceUrl', label: 'Workspace URL', type: 'text', placeholder: 'yourworkspace.slack.com' },
    { key: 'scanMode', label: 'Scan Mode', type: 'select', options: [{ value: 'realtime', label: 'Real-time (Events API)' }, { value: 'batch', label: 'Batch (Conversations API)' }, { value: 'discovery', label: 'Discovery (Enterprise Grid)' }] },
    { key: 'channels', label: 'Channels', type: 'textarea', placeholder: 'general, compliance-alerts' },
    { key: 'detectPII', label: 'Detect PII (Presidio)', type: 'checkbox' },
    { key: 'extractDocs', label: 'Extract Documents', type: 'checkbox' },
    { key: 'maxMessages', label: 'Max Messages', type: 'number', placeholder: '1000' },
  ],
  microsoftTeamsDORANode: [
    { key: 'tenantId', label: 'Tenant ID', type: 'text', placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' },
    { key: 'monitoringMode', label: 'Monitoring Mode', type: 'select', options: [{ value: 'ict_incidents', label: 'ICT Incidents' }, { value: 'resilience_testing', label: 'Resilience Testing' }, { value: 'third_party_risk', label: 'Third-Party Risk' }, { value: 'full_dora', label: 'Full DORA' }] },
    { key: 'alertWindow', label: 'Alert Window (minutes)', type: 'number', placeholder: '240' },
    { key: 'keywords', label: 'ICT Keywords', type: 'textarea', placeholder: 'outage, incident, breach, failure, downtime' },
    { key: 'teams', label: 'Team IDs', type: 'textarea', placeholder: 'Comma-separated Team IDs' },
    { key: 'integratePurview', label: 'Integrate Microsoft Purview', type: 'checkbox' },
  ],
  databaseCreatorNode: [
    { key: 'dbType', label: 'Database Type', type: 'select', options: [{ value: 'sqlite', label: 'SQLite (Local)' }, { value: 'postgresql', label: 'PostgreSQL (Docker)' }, { value: 'mysql', label: 'MySQL (Docker)' }, { value: 'mongodb', label: 'MongoDB (Docker)' }] },
    { key: 'databaseName', label: 'Database Name', type: 'text', placeholder: 'compliance_db' },
    { key: 'filePath', label: 'File Path (SQLite)', type: 'text', placeholder: '/path/to/database.db' },
    { key: 'encrypted', label: 'Encrypt (SQLCipher)', type: 'checkbox' },
    { key: 'initSchema', label: 'Init Schema (SQL)', type: 'textarea', placeholder: 'CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);' },
  ],
  localFolderStorageNode: [
    { key: 'operation', label: 'Operation', type: 'select', options: [{ value: 'list', label: 'List Files' }, { value: 'read', label: 'Read File' }, { value: 'write', label: 'Write File' }, { value: 'monitor', label: 'Monitor Changes' }] },
    { key: 'folderPath', label: 'Folder Path', type: 'text', placeholder: '/path/to/folder' },
    { key: 'filePattern', label: 'File Pattern', type: 'text', placeholder: '*.pdf, *.docx' },
    { key: 'recursive', label: 'Recursive', type: 'checkbox' },
  ],
  cloudDocumentNode: [
    { key: 'provider', label: 'Cloud Provider', type: 'select', options: [{ value: 'google_drive', label: 'Google Drive' }, { value: 'dropbox', label: 'Dropbox' }, { value: 'onedrive', label: 'OneDrive' }, { value: 'mega', label: 'MEGA (Encrypted)' }] },
    { key: 'operation', label: 'Operation', type: 'select', options: [{ value: 'list', label: 'List Files' }, { value: 'download', label: 'Download' }, { value: 'upload', label: 'Upload' }, { value: 'search', label: 'Search' }, { value: 'share', label: 'Share Link' }, { value: 'delete', label: 'Delete' }] },
    { key: 'folderId', label: 'Folder ID', type: 'text', placeholder: 'root or folder ID' },
    { key: 'query', label: 'Search Query', type: 'text', placeholder: 'name contains "compliance"' },
    { key: 'maxResults', label: 'Max Results', type: 'number', placeholder: '100' },
  ],
  jiraComplianceNode: [
    { key: 'jiraUrl', label: 'Jira URL', type: 'text', placeholder: 'https://yourcompany.atlassian.net' },
    { key: 'authType', label: 'Authentication', type: 'select', options: [{ value: 'oauth', label: 'OAuth 2.0 (3LO)' }, { value: 'token', label: 'API Token (Basic Auth)' }] },
    { key: 'email', label: 'Email (API Token)', type: 'text', placeholder: 'user@company.com' },
    { key: 'apiToken', label: 'API Token', type: 'password', placeholder: 'Jira API token' },
    { key: 'jqlQuery', label: 'JQL Query', type: 'textarea', placeholder: 'project = COMP AND status != Closed' },
    { key: 'analysisType', label: 'Analysis Type', type: 'select', options: [{ value: 'resolution_time', label: 'Resolution Time' }, { value: 'sla_compliance', label: 'SLA Compliance' }, { value: 'sprint_velocity', label: 'Sprint Velocity' }, { value: 'audit_trail', label: 'Audit Trail' }] },
    { key: 'includeChangelog', label: 'Include Changelog', type: 'checkbox' },
  ],
}
