import {
  Play,
  Database,
  Bot,
  Shield,
  MessageSquare,
  Container,
  FileText,
  FileSpreadsheet,
  Mail,
  Globe,
  UserCircle,
  ScrollText,
  FileCode,
  Plug,
  GitBranch,
  ShieldCheck,
  BarChart3,
  Brain,
  Archive,
  Scale,
  Lightbulb,
  Bug,
  Activity,
  Bell,
  Lock,
  Radio,
  Layers,
  HeartPulse,
  Landmark,
  FileCheck,
  UserCheck,
  ShieldAlert,
  DatabaseZap,
  FolderOpen,
  Cloud,
  Ticket,
  Building2,
} from 'lucide-react'
import { getNodeColorClass } from '../../../config/nodeColors'

export function NodeIcon({ type }: { type: string }) {
  const iconClass = "h-8 w-8 rounded-lg p-1.5"
  const colorClass = getNodeColorClass(type)

  const icons: Record<string, React.ReactNode> = {
    triggerNode: <Play size={20} className="text-white" />,
    databaseNode: <Database size={20} className="text-white" />,
    llmNode: <Bot size={20} className="text-white" />,
    piiFilterNode: <Shield size={20} className="text-white" />,
    outputNode: <MessageSquare size={20} className="text-white" />,
    dockerContainerNode: <Container size={20} className="text-white" />,
    documentNode: <FileText size={20} className="text-white" />,
    spreadsheetNode: <FileSpreadsheet size={20} className="text-white" />,
    emailInboxNode: <Mail size={20} className="text-white" />,
    webSearchNode: <Globe size={20} className="text-white" />,
    personalityNode: <UserCircle size={20} className="text-white" />,
    auditNode: <ScrollText size={20} className="text-white" />,
    codeReviewNode: <FileCode size={20} className="text-white" />,
    mcpContextNode: <Plug size={20} className="text-white" />,
    conditionalNode: <GitBranch size={20} className="text-white" />,
    approvalGateNode: <ShieldCheck size={20} className="text-white" />,
    complianceDashboardNode: <BarChart3 size={20} className="text-white" />,
    modelRegistryNode: <Brain size={20} className="text-white" />,
    evidenceCollectionNode: <Archive size={20} className="text-white" />,
    biasTestingNode: <Scale size={20} className="text-white" />,
    explainabilityNode: <Lightbulb size={20} className="text-white" />,
    redTeamingNode: <Bug size={20} className="text-white" />,
    driftDetectionNode: <Activity size={20} className="text-white" />,
    notificationNode: <Bell size={20} className="text-white" />,
    encryptionNode: <Lock size={20} className="text-white" />,
    webhookGatewayNode: <Radio size={20} className="text-white" />,
    subWorkflowNode: <Layers size={20} className="text-white" />,
    phiClassificationNode: <HeartPulse size={20} className="text-white" />,
    fairLendingNode: <Landmark size={20} className="text-white" />,
    claimsAuditNode: <FileCheck size={20} className="text-white" />,
    consentManagementNode: <UserCheck size={20} className="text-white" />,
    slackComplianceNode: <MessageSquare size={20} className="text-white" />,
    microsoftTeamsDORANode: <ShieldAlert size={20} className="text-white" />,
    databaseCreatorNode: <DatabaseZap size={20} className="text-white" />,
    localFolderStorageNode: <FolderOpen size={20} className="text-white" />,
    cloudDocumentNode: <Cloud size={20} className="text-white" />,
    jiraComplianceNode: <Ticket size={20} className="text-white" />,
    sapERPNode: <Building2 size={20} className="text-white" />,
  }

  const icon = icons[type]
  if (!icon) return null
  return <div className={`${iconClass} ${colorClass}`}>{icon}</div>
}
